"""Shared model catalog for CLI selections, validation, and web UI."""

from __future__ import annotations
from typing import Any

ModelOption = tuple[str, str]
ProviderModeOptions = dict[str, dict[str, list[ModelOption]]]

# Comprehensive Provider Model Catalog with rich metadata
PROVIDER_CATALOG: dict[str, list[dict[str, Any]]] = {
    "google": [
        {
            "id": "gemini-3.5-flash",
            "name": "Gemini 3.5 Flash",
            "provider": "google",
            "description": "Next-gen balanced model with high throughput and native tool use.",
            "context_window": 1048576,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.10 / 1M",
            "output_price": "$0.40 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_quick": True,
            "default_deep": False,
        },
        {
            "id": "gemini-3.8-flash",
            "name": "Gemini 3.8 Flash",
            "provider": "google",
            "description": "Ultra-low latency frontier Flash model for real-time market analysis.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.10 / 1M",
            "output_price": "$0.40 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
        },
        {
            "id": "gemini-3.7-flash",
            "name": "Gemini 3.7 Flash",
            "provider": "google",
            "description": "High-efficiency Flash model with hybrid thinking capabilities.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.10 / 1M",
            "output_price": "$0.40 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-3.6-flash",
            "name": "Gemini 3.6 Flash",
            "provider": "google",
            "description": "Frontier agentic model optimized for financial and technical workflows.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.10 / 1M",
            "output_price": "$0.40 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-3.1-pro-preview",
            "name": "Gemini 3.1 Pro Preview",
            "provider": "google",
            "description": "Deep reasoning flagship model for complex multi-agent debate and risk analysis.",
            "context_window": 1048576,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "input_price": "$1.25 / 1M",
            "output_price": "$5.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "gemini-3.5-flash-lite",
            "name": "Gemini 3.5 Flash Lite",
            "provider": "google",
            "description": "Ultra cost-efficient model with 1M context, ideal for high-frequency candidate sweeps.",
            "context_window": 1048576,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.05 / 1M",
            "output_price": "$0.20 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-3.1-flash-lite",
            "name": "Gemini 3.1 Flash Lite",
            "provider": "google",
            "description": "High quota, low latency preview model for automated scanning.",
            "context_window": 1048576,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.05 / 1M",
            "output_price": "$0.20 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-3-flash-preview",
            "name": "Gemini 3 Flash Preview",
            "provider": "google",
            "description": "Early preview of the Gemini 3 architecture.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-2.5-flash",
            "name": "Gemini 2.5 Flash",
            "provider": "google",
            "description": "Reliable 2.5 generation Flash model with high accuracy and low cost.",
            "context_window": 1048576,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.075 / 1M",
            "output_price": "$0.30 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
        },
        {
            "id": "gemini-2.5-pro",
            "name": "Gemini 2.5 Pro",
            "provider": "google",
            "description": "2.5 generation Pro model with deep contextual analysis.",
            "context_window": 1048576,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "input_price": "$1.25 / 1M",
            "output_price": "$5.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-2.5-flash-lite",
            "name": "Gemini 2.5 Flash Lite",
            "provider": "google",
            "description": "Lightweight, generous quota tier for continuous background polling.",
            "context_window": 1048576,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.05 / 1M",
            "output_price": "$0.20 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-flash-latest",
            "name": "Gemini Flash (Auto-Latest)",
            "provider": "google",
            "description": "Automatically points to the newest stable Gemini Flash model.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-pro-latest",
            "name": "Gemini Pro (Auto-Latest)",
            "provider": "google",
            "description": "Automatically points to the newest stable Gemini Pro model.",
            "context_window": 1048576,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-1.5-flash",
            "name": "Gemini 1.5 Flash",
            "provider": "google",
            "description": "Previous-gen cost-effective model.",
            "context_window": 1048576,
            "category": "Legacy",
            "lifecycle": "LEGACY",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gemini-1.5-pro",
            "name": "Gemini 1.5 Pro",
            "provider": "google",
            "description": "Previous-gen 2M context reasoning model.",
            "context_window": 2097152,
            "category": "Legacy",
            "lifecycle": "LEGACY",
            "speed": "Moderate",
            "cost_class": "High",
            "capabilities": {"reasoning": False, "tools": True, "vision": True, "json_mode": True},
        },
    ],
    "openai": [
        {
            "id": "gpt-4o",
            "name": "GPT-4o",
            "provider": "openai",
            "description": "Flagship multimodal intelligence with high speed and strong agentic function calling.",
            "context_window": 128000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "input_price": "$2.50 / 1M",
            "output_price": "$10.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_quick": True,
        },
        {
            "id": "gpt-4o-mini",
            "name": "GPT-4o Mini",
            "provider": "openai",
            "description": "Fast, lightweight frontier intelligence at a fraction of the cost.",
            "context_window": 128000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.15 / 1M",
            "output_price": "$0.60 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
        },
        {
            "id": "o3-mini",
            "name": "o3-mini",
            "provider": "openai",
            "description": "Specialized STEM and quantitative reasoning model with adjustable thinking effort.",
            "context_window": 200000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "input_price": "$1.10 / 1M",
            "output_price": "$4.40 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "o1",
            "name": "o1",
            "provider": "openai",
            "description": "Frontier reasoning model designed for complex multi-step market and risk analysis.",
            "context_window": 200000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "High",
            "input_price": "$15.00 / 1M",
            "output_price": "$60.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "o1-mini",
            "name": "o1-mini",
            "provider": "openai",
            "description": "Fast mathematical reasoning model.",
            "context_window": 128000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$1.10 / 1M",
            "output_price": "$4.40 / 1M",
            "capabilities": {"reasoning": True, "tools": False, "vision": False, "json_mode": True},
        },
        {
            "id": "gpt-4.5-preview",
            "name": "GPT-4.5 Preview",
            "provider": "openai",
            "description": "High-capacity preview model with vast world knowledge and nuanced judgment.",
            "context_window": 128000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Moderate",
            "cost_class": "High",
            "input_price": "$75.00 / 1M",
            "output_price": "$150.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gpt-5.6",
            "name": "GPT-5.6 (Frontier Sol)",
            "provider": "openai",
            "description": "Next-generation autonomous agentic reasoning model.",
            "context_window": 1000000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "High",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gpt-5.6-luna",
            "name": "GPT-5.6 Luna",
            "provider": "openai",
            "description": "High-throughput, cost-efficient variant of GPT-5.6.",
            "context_window": 1000000,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gpt-4-turbo",
            "name": "GPT-4 Turbo",
            "provider": "openai",
            "description": "Previous-gen flagship.",
            "context_window": 128000,
            "category": "Legacy",
            "lifecycle": "LEGACY",
            "speed": "Moderate",
            "cost_class": "High",
            "capabilities": {"reasoning": False, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "gpt-3.5-turbo",
            "name": "GPT-3.5 Turbo",
            "provider": "openai",
            "description": "Deprecated legacy chat model.",
            "context_window": 16385,
            "category": "Legacy",
            "lifecycle": "DEPRECATED",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
    ],
    "anthropic": [
        {
            "id": "claude-3-7-sonnet-latest",
            "name": "Claude 3.7 Sonnet",
            "provider": "anthropic",
            "description": "Hybrid architecture offering standard instant generation and extended deep thinking.",
            "context_window": 200000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "input_price": "$3.00 / 1M",
            "output_price": "$15.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "claude-3-5-sonnet-latest",
            "name": "Claude 3.5 Sonnet",
            "provider": "anthropic",
            "description": "Industry benchmark for tool calling, code generation, and financial analysis.",
            "context_window": 200000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "input_price": "$3.00 / 1M",
            "output_price": "$15.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_quick": True,
        },
        {
            "id": "claude-3-5-haiku-latest",
            "name": "Claude 3.5 Haiku",
            "provider": "anthropic",
            "description": "Near-frontier intelligence at sub-second response speeds and low cost.",
            "context_window": 200000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.80 / 1M",
            "output_price": "$4.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "claude-sonnet-5",
            "name": "Claude Sonnet 5",
            "provider": "anthropic",
            "description": "Next-gen balanced agentic intelligence.",
            "context_window": 250000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "claude-opus-4-8",
            "name": "Claude Opus 4.8",
            "provider": "anthropic",
            "description": "Frontier long-horizon reasoning and autonomous planning.",
            "context_window": 200000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "High",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "claude-3-opus-20240229",
            "name": "Claude 3 Opus",
            "provider": "anthropic",
            "description": "Previous-gen high capability model.",
            "context_window": 200000,
            "category": "Legacy",
            "lifecycle": "LEGACY",
            "speed": "Moderate",
            "cost_class": "High",
            "capabilities": {"reasoning": False, "tools": True, "vision": True, "json_mode": True},
        },
    ],
    "deepseek": [
        {
            "id": "deepseek-v4-flash",
            "name": "DeepSeek V4 Flash",
            "provider": "deepseek",
            "description": "Latest fast model supporting switchable thinking mode and high throughput.",
            "context_window": 128000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.14 / 1M",
            "output_price": "$0.28 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_quick": True,
        },
        {
            "id": "deepseek-v4-pro",
            "name": "DeepSeek V4 Pro",
            "provider": "deepseek",
            "description": "Flagship multi-step reasoning model with deep market debate capabilities.",
            "context_window": 128000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Low",
            "input_price": "$0.27 / 1M",
            "output_price": "$1.10 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "deepseek-chat",
            "name": "DeepSeek Chat (V3)",
            "provider": "deepseek",
            "description": "General purpose conversational and analytical model.",
            "context_window": 64000,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.14 / 1M",
            "output_price": "$0.28 / 1M",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "deepseek-reasoner",
            "name": "DeepSeek Reasoner (R1)",
            "provider": "deepseek",
            "description": "Reinforcement-learning trained pure reasoning model.",
            "context_window": 64000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Low",
            "input_price": "$0.55 / 1M",
            "output_price": "$2.19 / 1M",
            "capabilities": {"reasoning": True, "tools": False, "vision": False, "json_mode": True},
        },
    ],
    "kimi": [
        {
            "id": "kimi-k3",
            "name": "Kimi K3 (Flagship)",
            "provider": "kimi",
            "description": "Moonshot AI flagship with 1M context, native visual understanding and thinking modes.",
            "context_window": 1048576,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "kimi-k2.6",
            "name": "Kimi K2.6",
            "provider": "kimi",
            "description": "Fast agentic model with 256K context and switchable thinking modes.",
            "context_window": 256000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_quick": True,
        },
        {
            "id": "kimi-latest",
            "name": "Kimi Latest (Auto-Pointer)",
            "provider": "kimi",
            "description": "Always points to Moonshot's latest stable production model.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "moonshot-v1-128k",
            "name": "Moonshot v1 128K",
            "provider": "kimi",
            "description": "Long-context document and historical analysis model.",
            "context_window": 128000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Moderate",
            "cost_class": "Medium",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "moonshot-v1-32k",
            "name": "Moonshot v1 32K",
            "provider": "kimi",
            "description": "Mid-tier fast reasoning model.",
            "context_window": 32000,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "moonshot-v1-8k",
            "name": "Moonshot v1 8K",
            "provider": "kimi",
            "description": "Lightweight high-speed model.",
            "context_window": 8000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
    ],
    "nvidia": [
        {
            "id": "nvidia/llama-3.1-nemotron-70b-instruct",
            "name": "Nemotron 70B Instruct",
            "provider": "nvidia",
            "description": "NVIDIA-tuned Llama 3.1 with superior agentic reasoning and benchmark performance.",
            "context_window": 131072,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "nvidia/llama-3.1-nemotron-nano-8b-v1",
            "name": "Nemotron Nano 8B",
            "provider": "nvidia",
            "description": "Compact high-efficiency NIM model for rapid candidate screening.",
            "context_window": 131072,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_quick": True,
        },
        {
            "id": "meta/llama-3.3-70b-instruct",
            "name": "Llama 3.3 70B (NIM)",
            "provider": "nvidia",
            "description": "Meta frontier open model hosted on NVIDIA high-speed infrastructure.",
            "context_window": 131072,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "moonshotai/kimi-k3",
            "name": "Kimi K3 (NIM Hosted)",
            "provider": "nvidia",
            "description": "Moonshot Kimi K3 hosted on NVIDIA NIM.",
            "context_window": 1048576,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "deepseek-ai/deepseek-v4-pro-0813",
            "name": "DeepSeek V4 Pro (NIM)",
            "provider": "nvidia",
            "description": "DeepSeek V4 Pro hosted on NVIDIA NIM cluster.",
            "context_window": 131072,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "deepseek-ai/deepseek-v4-flash-0731",
            "name": "DeepSeek V4 Flash (NIM)",
            "provider": "nvidia",
            "description": "High-throughput DeepSeek V4 Flash hosted on NIM.",
            "context_window": 131072,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
    ],
    "meta": [
        {
            "id": "meta/llama-3.3-70b-instruct",
            "name": "Llama 3.3 70B Instruct",
            "provider": "meta",
            "description": "Frontier open-weights intelligence, matched with industry standard benchmarks.",
            "context_window": 128000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "meta/llama-3.1-8b-instruct",
            "name": "Llama 3.1 8B Instruct",
            "provider": "meta",
            "description": "Lightweight high-speed model for quick trend identification.",
            "context_window": 128000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
            "default_quick": True,
        },
        {
            "id": "meta/llama-3.1-405b-instruct",
            "name": "Llama 3.1 405B Instruct",
            "provider": "meta",
            "description": "Enormous 405B parameter model for deep macroeconomic synthesis.",
            "context_window": 128000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "High",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "muse-spark-1.3-contributor",
            "name": "Meta Muse Spark 1.3 (Contributor)",
            "provider": "meta",
            "description": "Contributor-tier long-context agentic model.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Free",
            "capabilities": {"reasoning": False, "tools": False, "vision": True, "json_mode": False},
        },
        {
            "id": "muse-spark-1.3",
            "name": "Meta Muse Spark 1.3 (Standard)",
            "provider": "meta",
            "description": "Standard 1M context multimodal model.",
            "context_window": 1048576,
            "category": "Multimodal",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": False, "vision": True, "json_mode": False},
        },
    ],
    "mistral": [
        {
            "id": "mistral-large-latest",
            "name": "Mistral Large (Latest)",
            "provider": "mistral",
            "description": "Top-tier reasoning model for complex multilingual and analytical tasks.",
            "context_window": 128000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "input_price": "$2.00 / 1M",
            "output_price": "$6.00 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "mistral-small-latest",
            "name": "Mistral Small (Latest)",
            "provider": "mistral",
            "description": "Fast and lightweight enterprise-grade model with low latency.",
            "context_window": 128000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.10 / 1M",
            "output_price": "$0.30 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "default_quick": True,
        },
        {
            "id": "ministral-8b-latest",
            "name": "Ministral 8B",
            "provider": "mistral",
            "description": "Powerful edge-scale model designed for high-frequency processing.",
            "context_window": 128000,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.10 / 1M",
            "output_price": "$0.10 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "ministral-3b-latest",
            "name": "Ministral 3B",
            "provider": "mistral",
            "description": "Extremely fast ultra-compact model with sub-second response times.",
            "context_window": 128000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.04 / 1M",
            "output_price": "$0.04 / 1M",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "codestral-latest",
            "name": "Codestral",
            "provider": "mistral",
            "description": "Specialized code and analytical computation model.",
            "context_window": 256000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "input_price": "$0.30 / 1M",
            "output_price": "$0.90 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
    ],
    "qwen": [
        {
            "id": "qwen3.7-max",
            "name": "Qwen 3.7 Max",
            "provider": "qwen",
            "description": "Alibaba Cloud flagship model with 1M context and frontier reasoning.",
            "context_window": 1048576,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "qwen3.7-plus",
            "name": "Qwen 3.7 Plus",
            "provider": "qwen",
            "description": "Balanced speed and intelligence with 1M context.",
            "context_window": 1048576,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
            "recommended": True,
            "default_quick": True,
        },
        {
            "id": "qwen3.6-max",
            "name": "Qwen 3.6 Max",
            "provider": "qwen",
            "description": "Previous-gen flagship with 1M context.",
            "context_window": 1048576,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "qwen3.6-plus",
            "name": "Qwen 3.6 Plus",
            "provider": "qwen",
            "description": "Previous-gen balanced model.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "qwen-max",
            "name": "Qwen Max (Auto-Pointer)",
            "provider": "qwen",
            "description": "Automatically routes to Alibaba's latest high-intelligence model.",
            "context_window": 32768,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "qwen-plus",
            "name": "Qwen Plus (Auto-Pointer)",
            "provider": "qwen",
            "description": "Balanced auto-upgrading pointer for general analysis.",
            "context_window": 131072,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "qwen-turbo",
            "name": "Qwen Turbo",
            "provider": "qwen",
            "description": "Fast and economical model for bulk screening.",
            "context_window": 131072,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
    ],
    "groq": [
        {
            "id": "llama-3.3-70b-versatile",
            "name": "Llama 3.3 70B Versatile",
            "provider": "groq",
            "description": "Ultra-high speed LPUs delivering frontier open intelligence at >300 tokens/sec.",
            "context_window": 128000,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.59 / 1M",
            "output_price": "$0.79 / 1M",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "llama-3.1-8b-instant",
            "name": "Llama 3.1 8B Instant",
            "provider": "groq",
            "description": "Near instantaneous inference at over 800 tokens/sec.",
            "context_window": 128000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.05 / 1M",
            "output_price": "$0.08 / 1M",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
            "default_quick": True,
        },
        {
            "id": "mixtral-8x7b-32768",
            "name": "Mixtral 8x7B",
            "provider": "groq",
            "description": "High-throughput Mixture-of-Experts model.",
            "context_window": 32768,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "input_price": "$0.24 / 1M",
            "output_price": "$0.24 / 1M",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "qwen-2.5-32b",
            "name": "Qwen 2.5 32B",
            "provider": "groq",
            "description": "High-speed reasoning model powered by Groq LPUs.",
            "context_window": 128000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
    ],
    "openrouter": [
        {
            "id": "nvidia/nemotron-3-super-120b-a12b:free",
            "name": "NVIDIA Nemotron 3 Super 120B (Free)",
            "provider": "openrouter",
            "description": "Generous free-tier frontier reasoning model hosted on OpenRouter.",
            "context_window": 131072,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Free",
            "input_price": "Free",
            "output_price": "Free",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_quick": True,
            "default_deep": True,
        },
        {
            "id": "deepseek/deepseek-chat",
            "name": "DeepSeek V3 (OpenRouter)",
            "provider": "openrouter",
            "description": "Fast and economical open weights model via OpenRouter API.",
            "context_window": 64000,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "deepseek/deepseek-r1",
            "name": "DeepSeek R1 (OpenRouter)",
            "provider": "openrouter",
            "description": "Pure reasoning model with step-by-step thinking.",
            "context_window": 64000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": False, "vision": False, "json_mode": True},
        },
        {
            "id": "google/gemini-2.5-flash",
            "name": "Google Gemini 2.5 Flash",
            "provider": "openrouter",
            "description": "Google's high speed 1M context model routed via OpenRouter.",
            "context_window": 1048576,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "google/gemini-2.0-flash-exp:free",
            "name": "Google Gemini 2.0 Flash Exp (Free)",
            "provider": "openrouter",
            "description": "Free-tier multimodal model routed via OpenRouter.",
            "context_window": 1048576,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Free",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "meta-llama/llama-3.3-70b-instruct",
            "name": "Llama 3.3 70B Instruct",
            "provider": "openrouter",
            "description": "Meta's flagship open model routed through OpenRouter.",
            "context_window": 131072,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "anthropic/claude-3.5-sonnet",
            "name": "Claude 3.5 Sonnet (OpenRouter)",
            "provider": "openrouter",
            "description": "Anthropic's frontier model accessed via unified OpenRouter credentials.",
            "context_window": 200000,
            "category": "Advanced",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
        {
            "id": "openai/gpt-4o-mini",
            "name": "OpenAI GPT-4o Mini",
            "provider": "openrouter",
            "description": "Fast and low-cost OpenAI model via OpenRouter.",
            "context_window": 128000,
            "category": "Low Cost",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": True, "tools": True, "vision": True, "json_mode": True},
        },
    ],
    "xai": [
        {
            "id": "grok-4.3",
            "name": "Grok 4.3",
            "provider": "xai",
            "description": "Latest flagship model from xAI with built-in real-time reasoning and 1M context.",
            "context_window": 1048576,
            "category": "Recommended",
            "lifecycle": "ACTIVE",
            "speed": "Fast",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
            "recommended": True,
            "default_deep": True,
        },
        {
            "id": "grok-4.20-0309-reasoning",
            "name": "Grok 4.20 Reasoning",
            "provider": "xai",
            "description": "Deep reasoning model for high-stakes financial analysis.",
            "context_window": 256000,
            "category": "Reasoning",
            "lifecycle": "ACTIVE",
            "speed": "Deep Reasoning",
            "cost_class": "Medium",
            "capabilities": {"reasoning": True, "tools": True, "vision": False, "json_mode": True},
        },
        {
            "id": "grok-4.20-0309-non-reasoning",
            "name": "Grok 4.20 Fast",
            "provider": "xai",
            "description": "Speed-optimized variant for rapid screening.",
            "context_window": 256000,
            "category": "Fast",
            "lifecycle": "ACTIVE",
            "speed": "Ultra Fast",
            "cost_class": "Low",
            "capabilities": {"reasoning": False, "tools": True, "vision": False, "json_mode": True},
            "default_quick": True,
        },
    ],
}

# Automatically populate dual-region endpoints for Qwen, GLM, and MiniMax
PROVIDER_CATALOG["qwen-cn"] = PROVIDER_CATALOG["qwen"]


# Build the legacy MODEL_OPTIONS dictionary for backward-compatibility with CLI and tests
MODEL_OPTIONS: ProviderModeOptions = {}

for prov, mlist in PROVIDER_CATALOG.items():
    quick_opts: list[ModelOption] = []
    deep_opts: list[ModelOption] = []
    
    for m in mlist:
        label = f"{m['name']} - {m['description'][:48]}"
        val = m["id"]
        # If model is not legacy, include in quick/deep lists
        if m.get("lifecycle") != "DEPRECATED":
            if m.get("category") in {"Recommended", "Fast", "Low Cost"}:
                quick_opts.append((label, val))
            if m.get("category") in {"Recommended", "Reasoning", "Advanced"}:
                deep_opts.append((label, val))
    
    # Fallback to ensure at least one option exists
    if not quick_opts:
        quick_opts = [(f"{m['name']}", m["id"]) for m in mlist[:4]]
    if not deep_opts:
        deep_opts = [(f"{m['name']}", m["id"]) for m in mlist[:4]]
        
    quick_opts.append(("Custom model ID", "custom"))
    deep_opts.append(("Custom model ID", "custom"))

    MODEL_OPTIONS[prov] = {
        "quick": quick_opts,
        "deep": deep_opts,
    }

# Ensure fallback keys exist
for key in ["azure", "openai_compatible", "bedrock", "ollama"]:
    if key not in MODEL_OPTIONS:
        MODEL_OPTIONS[key] = {
            "quick": [("Custom model ID", "custom")],
            "deep": [("Custom model ID", "custom")],
        }


def get_model_options(provider: str, mode: str) -> list[ModelOption]:
    """Return shared model options for a provider and selection mode."""
    p = provider.lower()
    if p in MODEL_OPTIONS:
        return MODEL_OPTIONS[p].get(mode, [("Custom model ID", "custom")])
    return [("Custom model ID", "custom")]


def get_known_models() -> dict[str, list[str]]:
    """Build known model names from the shared catalog."""
    known: dict[str, set[str]] = {}
    for provider, mlist in PROVIDER_CATALOG.items():
        known[provider] = {m["id"] for m in mlist}
    
    for provider, modes in MODEL_OPTIONS.items():
        if provider not in known:
            known[provider] = set()
        for opts in modes.values():
            for _, val in opts:
                if val != "custom":
                    known[provider].add(val)

    return {prov: sorted(list(ids)) for prov, ids in known.items()}


def get_model_metadata(provider: str, model_id: str) -> dict[str, Any] | None:
    """Find specific model metadata by provider and ID."""
    p = provider.lower()
    for m in PROVIDER_CATALOG.get(p, []):
        if m["id"] == model_id:
            return m
    return None
